#!/usr/bin/env zsh
# AI Usage Collect - Install Script
# Sets up the client-side hooks and collector for a developer workstation.

set -e

echo "╔══════════════════════════════════════════╗"
echo "║   AI Usage Collect - Installer           ║"
echo "╚══════════════════════════════════════════╝"
echo ""

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# =============================================================================
# Gather configuration
# =============================================================================

echo -n "Team name (e.g. infrastructure, frontend, backend): "
read TEAM
if [[ -z "$TEAM" ]]; then
  echo "❌ Team name is required."
  exit 1
fi

echo -n "API endpoint URL [https://YOUR_USAGE_API_ENDPOINT]: "
read API_ENDPOINT
API_ENDPOINT="${API_ENDPOINT:-https://YOUR_USAGE_API_ENDPOINT}"

echo -n "API key: "
read -s API_KEY
echo ""
if [[ -z "$API_KEY" ]]; then
  echo "❌ API key is required."
  exit 1
fi

# =============================================================================
# Create directories
# =============================================================================

mkdir -p "$HOME/.ai-usage"
mkdir -p "$HOME/.local/bin"
mkdir -p "$HOME/.kiro/hooks"

# =============================================================================
# Write config
# =============================================================================

cat > "$HOME/.ai-usage/config.env" << EOF
# AI Usage Collect Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
TEAM="$TEAM"
API_ENDPOINT="$API_ENDPOINT"
API_KEY="$API_KEY"
EOF

chmod 600 "$HOME/.ai-usage/config.env"
echo "✅ Config written to ~/.ai-usage/config.env"

# =============================================================================
# Install allowed tags validation file
# =============================================================================

cp "$SCRIPT_DIR/allowed_tags.json" "$HOME/.ai-usage/allowed_tags.json"
echo "✅ Allowed tags installed to ~/.ai-usage/allowed_tags.json"

# =============================================================================
# Install collector script
# =============================================================================

cp "$SCRIPT_DIR/bin/ai-usage-collect" "$HOME/.local/bin/ai-usage-collect"
chmod +x "$HOME/.local/bin/ai-usage-collect"
echo "✅ Collector installed to ~/.local/bin/ai-usage-collect"

# =============================================================================
# Install hooks (user-level, applies to all workspaces)
# =============================================================================

cp "$SCRIPT_DIR/hooks/classify-hook.kiro.hook" "$HOME/.kiro/hooks/classify-hook.kiro.hook"
echo "✅ Classify hook installed to ~/.kiro/hooks/"

# Also install to current workspace if .kiro exists
if [[ -d ".kiro" ]]; then
  mkdir -p ".kiro/hooks"
  cp "$SCRIPT_DIR/hooks/classify-hook.kiro.hook" ".kiro/hooks/classify-hook.kiro.hook"
  echo "✅ Hook also installed to workspace .kiro/hooks/"
fi

# =============================================================================
# Verify PATH
# =============================================================================

if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
  echo ""
  echo "⚠️  ~/.local/bin is not in your PATH."
  echo "   Add this to your ~/.zshrc:"
  echo "   export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

echo ""
echo "🎉 Installation complete!"
echo ""
echo "How it works:"
echo "  • On each agentStop event, Kiro classifies the session"
echo "  • Assigns governance tags (Project, Application, Brand, CostCenter, Environment, Owner)"
echo "  • Validates tags against allowed_tags.json before sending"
echo "  • Sends usage event with credits to the tracking API"
echo ""
echo "Verify with:"
echo "  which ai-usage-collect"
echo "  cat ~/.ai-usage/config.env"
echo "  ls ~/.kiro/hooks/classify-hook.kiro.hook"
